name: Deploy PR previews

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]

concurrency:
  group: preview-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build library
        if: github.event.action != 'closed'
        run: |
          corepack enable
          corepack pnpm install --frozen-lockfile
          corepack pnpm build
          cp dist/index.js docs/index.js
      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./docs/
          preview-branch: gh-pages
